# Use Alpine as the base image due to its small size
FROM arm64v8/alpine:3.18.3

# Set Timezone
ENV TZ="Asia/Bangkok"

# Set the working directory inside the container
WORKDIR /app

# Install curl
RUN apk add --no-cache curl jq

# Copy the script to run curl periodically
COPY run.sh .
COPY settings.json .

# Make the script executable
RUN chmod +x run.sh

# Command to run the script
CMD ["./run.sh"]
